global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']  # если не работает — просто убери этот job